
// Tipos de acción para las razas de perros
export const GET_ALL_DOGS_REQUEST = 'GET_ALL_DOGS_REQUEST';
export const GET_ALL_DOGS_SUCCESS = 'GET_ALL_DOGS_SUCCESS';
export const GET_ALL_DOGS_FAILURE = 'GET_ALL_DOGS_FAILURE';

export const GET_DOG_DETAIL_REQUEST = 'GET_DOG_DETAIL_REQUEST';
export const GET_DOG_DETAIL_SUCCESS = 'GET_DOG_DETAIL_SUCCESS';
export const GET_DOG_DETAIL_FAILURE = 'GET_DOG_DETAIL_FAILURE';

export const GET_DOG_BY_NAME_REQUEST = 'GET_DOG_BY_NAME_REQUEST';
export const GET_DOG_BY_NAME_SUCCESS = 'GET_DOG_BY_NAME_SUCCESS';
export const GET_DOG_BY_NAME_FAILURE = 'GET_DOG_BY_NAME_FAILURE';

export const GET_DOG_BY_ID_REQUEST = 'GET_DOG_BY_ID_REQUEST'
export const GET_DOG_BY_ID_SUCCESS = 'GET_DOG_BY_ID_SUCCESS'
export const GET_DOG_BY_ID_FAILURE = 'GET_DOG_BY_ID_FAILURE'

export const CREATE_DOG_REQUEST = 'CREATE_DOG_REQUEST';
export const CREATE_DOG_SUCCESS = 'CREATE_DOG_SUCCESS';
export const CREATE_DOG_FAILURE = 'CREATE_DOG_FAILURE';

// Tipos de acción para los temperamentos
export const GET_TEMPERAMENTS_REQUEST = 'GET_TEMPERAMENTS_REQUEST';
export const GET_TEMPERAMENTS_SUCCESS = 'GET_TEMPERAMENTS_SUCCESS';
export const GET_TEMPERAMENTS_FAILURE = 'GET_TEMPERAMENTS_FAILURE';
